model:
  branch_layers : [100, 128, 128, 128]
  trunk_layers : [3, 128, 128, 128]
  loss_type : 'huber'
  # huber_delta : 0.5**2
  huber_delta : 0.4

global:
  Nx : 100
  Nt : 100
  kappa : 1.0 # tried = 1
  period : 1 # rho
  T_lim : 1 # T

train:
  N_train : [400]
  # P_train : [500, 750, 1000, 1500, 2000, 2500, 3550, 4000] 
  P_train : [200, 300, 400, 500, 750, 1000, 1500, 2000, 2500]
  num_sine_terms : 3
  sine_amplitude : 0.2

test:
  N_test : 100
  P_test : 20

plot:
  P_test : 121
  N_test : 1